variant-calls:
  # Listing of callsets and corresponding paths, representing variant call results
  # from different pipelines or different configurations of the same pipeline.
  # Multiple entries are possible.
  # TODO add again once new token provided
  # bonn-core-unit-agilent-200M:
  #   labels:
  #     site: bonn-core-unit
  #     reads: 200M
  #   subcategory: NA12878-agilent
  #   benchmark: giab-NA12878-agilent-200M
  #   rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  #   zenodo:
  #     deposition: 6541919
  #     restricted-access-token-envvar: BO_CORE_UNIT_TOKEN
  #     filename: 118711_200M.vcf.gz
  # bonn-core-unit-agilent-75M:
  #   labels:
  #     site: bonn-core-unit
  #     reads: 75M
  #   subcategory: NA12878-agilent
  #   benchmark: giab-NA12878-agilent-75M
  #   rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  #   zenodo:
  #     deposition: 6541919
  #     restricted-access-token-envvar: BO_CORE_UNIT_TOKEN
  #     filename: 118711_75M.vcf.gz
  # bonn-core-unit-twist:
  #   labels:
  #     site: bonn-core-unit
  #   subcategory: NA12878-twist
  #   benchmark: giab-NA12878-twist
  #   rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  #   zenodo:
  #     deposition: 6541919
  #     restricted-access-token-envvar: BO_CORE_UNIT_TOKEN
  #     filename: NA12878_HG001_Twist.vcf.gz
  # TODO uncomment once WGS is available via zenodo
  # bonn-core-unit-na24385-wgs:
  #   labels:
  #     site: bonn-core-unit
  #   subcategory: NA12878-WGS
  #   benchmark: giab-NA12878-wgs
  #   zenodo:
  #     deposition: 6541919
  #     restricted-access-token-envvar: BO_CORE_UNIT_TOKEN
  #     filename: A006200148.vcf.gz
  # TODO uncomment once CHM download works again via sra ftp
  # bonn-core-unit-chm:
  #   labels:
  #     site: bonn-core-unit
  #   subcategory: CHM-eval
  #   benchmark: chm-eval
  #   rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  #   zenodo:
  #     deposition: 6541919
  #     restricted-access-token-envvar: BO_CORE_UNIT_TOKEN
  #     filename: PRJEB13208_hg38.vcf.gz
  BO-agilent-200M:
    labels:
      site: bonn-cropbio
      reads: 200M
    subcategory: NA12878-agilent
    zenodo:
      deposition: 6472481
      restricted-access-token-envvar: BO_AGILENT_TOKEN
      filename: cropbioBonn_WGGC_WES_CN_200M.vcf.gz
    benchmark: giab-NA12878-agilent-200M
  CO-agilent-200M:
    labels:
      site: cologne
      reads: 200M
    subcategory: NA12878-agilent
    zenodo:
      deposition: 6516963
      restricted-access-token-envvar: CO_AGILENT_TOKEN
      filename: NA12878_200M_SID118711_AID130848.cmb.func.vcf.gz
    benchmark: giab-NA12878-agilent-200M
  CO-agilent-75M:
    labels:
      site: cologne
      reads: 75M
    subcategory: NA12878-agilent
    zenodo:
      deposition: 6516963
      restricted-access-token-envvar: CO_AGILENT_TOKEN
      filename: NA12878_75M_SID118711_AID130010.cmb.func.vcf.gz
    benchmark: giab-NA12878-agilent-75M

  # DD-gatk-agilent:
  #   labels:
  #     site: DD
  #     pipeline: gatk
  #     reads: 200M
  #   subcategory: agilent
  #   path: resources/ftp/wes_agilentv7/DD_NA12878.gatk.vcf.gz
  #   benchmark: giab-NA12878-agilent-200M
  #   rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  # GHGA-haplotypecaller-agilent:
  #   labels:
  #     site: GHGA
  #     pipeline: gatk
  #     reads: 200M
  #   subcategory: agilent
  #   path: resources/ftp/wes_agilentv7/GHGA_haplotypecaller_A006850052.vcf.gz
  #   benchmark: giab-NA12878-agilent-200M
  #   rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  # KI-agilent:
  #   labels:
  #     site: KI
  #     reads: 200M
  #   subcategory: agilent
  #   path: resources/ftp/wes_agilentv7/KI_Indiv_A006850052_118711_Sample_A006850052_118711.dedup.vcf.gz
  #   benchmark: giab-NA12878-agilent-200M
  #   rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-sarek-freebayes-agilent-200M:
    labels:
      site: TB QBiC
      pipeline: nf-core/sarek v2.7 freebayes
      reads: 200M
    subcategory: NA12878-agilent
    zenodo:
      deposition: 6556340
      filename: WES_high_coverage_FreeBayes_NA12878.vcf.gz
    benchmark: giab-NA12878-agilent-200M
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-sarek-haplotypecaller-agilent-200M:
    labels:
      site: TB QBiC
      pipeline: nf-core/sarek v2.7 haplotypecaller
      reads: 200M
    subcategory: NA12878-agilent
    zenodo:
      deposition: 6556340
      filename: WES_high_coverage_HaplotypeCaller_NA12878.vcf.gz
    benchmark: giab-NA12878-agilent-200M
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-sarek-strelka-agilent-200M:
    labels:
      site: TB QBiC
      pipeline: nf-core/sarek v2.7 strelka
      reads: 200M
    subcategory: NA12878-agilent
    zenodo:
      deposition: 6556340
      filename: WES_high_coverage_Strelka_NA12878_variants.vcf.gz
    benchmark: giab-NA12878-agilent-200M
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-sarek-freebayes-agilent-75M:
    labels:
      site: TB QBiC
      pipeline: nf-core/sarek v2.7 freebayes
      reads: 75M
    subcategory: NA12878-agilent
    zenodo:
      deposition: 6556340
      filename: WES_low_coverage_FreeBayes_NA12878.vcf.gz
    benchmark: giab-NA12878-agilent-75M
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-sarek-haplotypecaller-agilent-75M:
    labels:
      site: TB QBiC
      pipeline: nf-core/sarek v2.7 haplotypecaller
      reads: 75M
    subcategory: NA12878-agilent
    zenodo:
      deposition: 6556340
      filename: WES_low_coverage_HaplotypeCaller_NA12878.vcf.gz
    benchmark: giab-NA12878-agilent-75M
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-sarek-strelka-agilent-75M:
    labels:
      site: TB QBiC
      pipeline: nf-core/sarek v2.7 strelka
      reads: 75M
    subcategory: NA12878-agilent
    zenodo:
      deposition: 6556340
      filename: WES_low_coverage_Strelka_NA12878_variants.vcf.gz
    benchmark: giab-NA12878-agilent-75M
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  # TB-ngscn-agilent:
  #   labels:
  #     site: TB
  #     pipeline: ngscn
  #     reads: 200M
  #   subcategory: agilent
  #   path: resources/ftp/wes_agilentv7/TB_NGSCN-benchmark-NCCT_var.vcf.gz
  #   benchmark: giab-NA12878-agilent-200M
  #   rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt

  DUE-varlociraptor:
    zenodo:
      deposition: 6396505
      filename: NA12878.present.fdr-controlled.bcf
    benchmark: giab-NA12878-agilent-200M
    subcategory: NA12878-agilent
    labels:
      site: duisburg-essen
      pipeline: dna-seq-varlociraptor
      reads: 200M


# Optional: paths to custom read data, instead of downloading public exome dataset.
custom-benchmarks:
  giab-NA12878-agilent-200M:
    zenodo:
      deposition: 6513789
    genome: na12878
    fastqs:
      - resources/zenodo/custom-benchmarks/giab-NA12878-agilent-200M/A006850052_NA12878_200M_R1.fq.gz
      - resources/zenodo/custom-benchmarks/giab-NA12878-agilent-200M/A006850052_NA12878_200M_R2.fq.gz
    target-regions: resources/zenodo/custom-benchmarks/giab-NA12878-agilent-200M/Agilent_v7.bed
    # whether given target regions are on hg19
    grch37: false
  giab-NA12878-agilent-75M:
    zenodo:
      deposition: 6513789
    genome: na12878
    fastqs:
      - resources/zenodo/custom-benchmarks/giab-NA12878-agilent-75M/A006850052_NA12878_75M_R1.fq.gz
      - resources/zenodo/custom-benchmarks/giab-NA12878-agilent-75M/A006850052_NA12878_75M_R2.fq.gz
    target-regions: resources/zenodo/custom-benchmarks/giab-NA12878-agilent-200M/Agilent_v7.bed # same bed as 200M
    # whether given target regions are on hg19
    grch37: false
  # TODO comment in once new token has been granted
  # giab-NA12878-twist:
  #   zenodo:
  #     deposition: 6907125
  #     restricted-access-token-envvar: BENCHMARK_GIAB_NA12878_TWIST_TOKEN
  #   genome: na12878
  #   fastqs:
  #     - resources/zenodo/custom-benchmarks/giab-NA12878-twist/DE47NGSUKBD116105_76321_1.fq.gz
  #     - resources/zenodo/custom-benchmarks/giab-NA12878-twist/DE47NGSUKBD116105_76321_2.fq.gz
  #   target-regions: resources/https/www.twistbioscience.com/sites/default/files/resources/2022-01/Twist_Comprehensive_Exome_Covered_Targets_hg38.bed
  #   # whether given target regions are on hg19
  #   grch37: false

# Optional: limit testing and downloading to given regions
limit-regions:
  activate: false

# Set to true to run analysis on GRCh37 instead of GRCh38
grch37: false
